### ISSUE TITLE
No minification(-nomin) result is not the same when execute

### ISSUE THREAD

**Issue by warrenchopin** [QQuick/Transcrypt#672]
Transcypt compilation time becomes too slow as the size and the number of source files grows. So, I tried to compile without minification by adding -nomin option. It is a lot faster!!! But unfortunately the execute result is not the same. Usually, the non-minified result throws an unpredictable error while the usual result has no error

It seems that -nomin option is not tested well because it is not default. How about setting -nomin option as default? Most time, programmers compiles a debug version, and a minified version is tested only at the end of development for distribution.

I found that most compilation time was occupied by the minification process. Without minification, the compilation time got over 10 times faster. 

Is there any comment how to reduce compilation time?

**Comment by warrenchopin** [comment]
When I used Brython, the compile time was near zero second per a page. You can see how fast it is to compile Python to Javascript code. 

But Transcrypt is waaaaaay too slow in compilation. I think that Transcrypt itself is not slow. The time killer is minification. But -nomin  option is malfunctioning now (so sad).  If possible, please make -nomin option default so that this option is tested always. 

Also, I tried to compile only a modified source, but it also didn't work. It may be related minification. It seems that the main target js file includes all sub modules. So, compiling a modified source is not enough in default mode. Transcrypt checks the only update file to compile, but it is still way to slow.

I think that fixing -nomin option is the best way.. I am hoping that I can compiled a modified source and run it immediately under this option.

**Comment by warrenchopin** [comment]
Following is the error message when compiled with -nomin option. 
> Error while compiling (offending file last):
>         ...
>         File 'slgilib.network.Wrpc', line 0, namely:
>         'cp949' codec can't decode byte 0xec in position 2337: illegal multibyte sequence
> Aborted

This error is always raised from the second compilation. The first compile doesn't throw an error, however the execute result usually ends up unpredictable failure.  Without -nomin option, no error is raised, but compilation speed is painfully slow.

I hope this bug is fixed soon because the compilation is too slow (over several minutes) and it is really pain for development.

**Comment by fzzylogic** [comment]
@warrenchopin This doesn't solve your problem, but it might be useful to know that minification is done with [Google's Closure](https://www.transcrypt.org/docs/html/installation_use.html#installation-troubleshooting-checklist). So, one could use the nomin option and then afterwards minify with another minifier (a faster one). But not minifying during development is the fastest way to go.

Regarding the encoding problem, it might relate to one or more of [3 things](https://github.com/QQuick/Transcrypt/issues/361#issuecomment-315924471): 1) The encoding used by the shell (check using 'locale' for example on bash / systeminfo | find "Locale" with cmd.exe / Get-UICulture or Get-Host under PowerShell), 2) The encoding of the file itself and 3) the encoding that Python decides to use (which is not based on the encoding of the file, but rather [it uses your environment to choose an encoding](https://docs.python.org/3.7/library/functions.html#open)). Quote from the docs: 

> _encoding_ is the name of the encoding used to decode or encode the file. This should only be used in text mode. The default encoding is platform dependent (whatever [locale.getpreferredencoding()](https://docs.python.org/3.7/library/locale.html#locale.getpreferredencoding) returns), but any [text encoding](https://docs.python.org/3.7/glossary.html#term-text-encoding) supported by Python can be used. See the [codecs](https://docs.python.org/3.7/library/codecs.html#module-codecs) module for the list of supported encodings.

I notice cp949 codec is being used, so possibly you're using Windows on a computer with a Korean locale and it might then be that the files you're compiling contain characters that can't be coerced to anything that codec knows about.

In the past i had problems getting windows cmd.exe to work well with unicode and would also get these sorts of encoding errors when compiling files containing chinese and korean characters that worked fine under bash / linux, but Python launched from cmd.exe was using the wrong encoding to open them, despite my best efforts to force the shell to use utf-8. In my case, i didn't go the route of explicitly specifying the encoding to Python (for example in the open command), instead i switched to a more cooperative shell, specifically bash under WSL (Windows Subsystem for Linux). 

Hope that helps and please post your findings, it can help others in future.

**Comment by warrenchopin** [comment]
@fzzylogic Are you using Transcrypt with -nomin option without a problem? I want to know whether it is an encoding problem outside Transcrypt. But I am still wondering about why it has no problem without -nomin option if the encoding problem is the reason.

**Comment by fzzylogic** [comment]
@warrenchopin Good question, it could only make sense if Transcrypt does something different with the encoding of minified files vs non-minified files. 

-n (aka --nomin) does work for my light use, but you may be using Transcrypt features I'm not and could have found a bug, so getting to the bottom of it can be very helpful and any details you share might help.

As an example, i used a very simple one file [transcrypt game demo](https://github.com/fzzylogic/phaser3_transcrypt_tutorial) from two years ago. I downloaded it and compiled it with the latest pip version of Transcrypt 3.7.16 (under cmd.exe on Windows), using just:

    transcrypt -n game.py

Though there was no codec error, there was a js module error. So i googled the error and learned that i had to change type="text/javascript" to type="module". After that the demo worked in two ES6 compatible browsers i tested it on (note that the minifier has the capability to [convert a number of ES6 features to work on ES5 browers](https://github.com/google/closure-compiler/wiki/ECMAScript6), but it won't do anything about ES6 module imports).

So i tried adding a variable with a chinese character for a name:

    永 = "foo"

But that also worked. I checked the codepage for the console using 'chcp' and it returned 437. So i looked inside the transcrypt source (since 437 should have caused a codec error) and noticed the [create utility](https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/org/transcrypt/utils.py) explicitly uses encoding = 'utf-8' now when opening files (so it's not inheriting from the shell anymore), so i took that out of utils.py. It still seemed to work, but then i remembered to use the -b switch. That forces Transcrypt to delete all files in the target folder and re-compile everything instead of only new things. Then it finally gave a codec error because of the chinese character not being understood by the codec. 

To make sure that was the problem (since it said line 0 but i put the character on line 164), i took out the chinese character and compiling worked again.

But the error is different to the error you're getting, which might be happening because you're using files encoded in cp949 encoding. Since it's trying to open the file in cp949 format, i looked a bit in [compiler.py](https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/org/transcrypt/compiler.py) and noticed that when not using the -b option, files that are opened will not be explicitly opened as utf-8 (line 220). But i'm going too far with guessing here. Hope something above helps.

**Comment by warrenchopin** [comment]
Adding '-b' option works without an error.  (-b -nomin) or (-b -n). Although it compiles everything, the speed is fast enough compared to using -nomin option only.  I am using Window XP, and Transcrypt v3.7.16.
@fzzylogic 
> i looked a bit in compiler.py and noticed that when not using the -b option, files that are opened will not be explicitly opened as utf-8 (line 220).

You are right. it seems that the source is opened without explicit 'utf-8' option when  compiled with-nomin option. Thank you so much for your help.
